#! /usr/bin/env python
# 
#    extractdft: a python script to print the output energies from Gaussian optimizations from the command line
#    modified from the original function written by Aaron Danilack
#    Usage: $ extractdft file1.log file2.log ...
#    Copyright (C) 2020  Mark E. Fuller
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#    Mark E. Fuller: mark.e.fuller@gmx.de


#setup terminal output later:
#    extractdft  Copyright (C) 2020  Mark E. Fuller
#    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
#    This is free software, and you are welcome to redistribute it
#    under certain conditions; type `show c' for details.


################################################################################


# Import stuff.
import sys

print('\n')

for filename in sys.argv[1:]: 

	E0 = [] # Fill this list with E0 lines.
	ZPE = [] # Fill this list with ZPE lines.

	# Get the data from the geometry optimization calculation.
	with open (filename, 'r') as logfile:
	    loglines = logfile.readlines()

	for (l,line) in enumerate(loglines):
	    if line.startswith(' Sum of electronic and zero-point Energies='):
		    E0.append(line)
	    elif line.startswith(' Zero-point correction='):
		    ZPE.append(line)

	# Print the data we want.
	print(filename) 
	print('E0+ZPE = ' + str(E0[-1].split()[-1]))
	print('ZPE = ' + str(ZPE[-1].split()[-2]))	 
	print('\n')                          
