#! /usr/bin/env python
# M.E. Fuller, 13 APR 2020
# Adapted from the function g09_to_paper.py of:
# Franklin Goldsmith
# Brown University
# Goldsmith Research Group
# Created: ~2016 (?)
# originally prepared MESS/PAPER input from g09 output

# Title: writescan
# Description: A python script to generate g09/g16 scan input files (templated) from g09/g16 output
# Inputs: sys.argv[1:] = Gaussian optimization log files
# Usage: $ writescan file1 file2 ...

################################################################################

# Import stuff.
import re # regular expressions
import fileinput, sys, os
import time
import shutil


for gfilename in sys.argv[1:]: 
	ifilename = gfilename.replace('.log','.gjf')

	with open(ifilename, 'r')as ifile:
		ifilelines = ifile.readlines()

	newline = ''

	#copy input file information with req'd updates
	for (l,line) in enumerate(ifilelines):
		if line.startswith('%chk'):
			line = line.replace('.chk','_scan_.chk')
		elif line.startswith("#p"):
			line = line.replace('internal','modredundant')
		elif line.startswith('   B1'):
			break
		
		newline += line


	#get results of calculation
	with open(gfilename, 'r')as gfile:
		gfilelines = gfile.readlines()	

	start_freq = False
	for (l,line) in enumerate(gfilelines):
		if line.startswith(" Optimization completed"):
			if gfilelines[l+1].startswith("    -- Stationary point found."):
				start_freq = True

		if (start_freq == True) and (line.startswith('                       !   Optimized Parameters')):
			geom = ''
			for i in range(1000):
				localline =  gfilelines[l+5+i]
				if localline.startswith(' ---------'):
					break
				else:
					bits = localline.split()
					geom += '   ' + bits[1] + '\t' + bits[2] + '\n'
			break


	scanline = newline + geom	

	sfilename = gfilename.replace('.log','_scan_.gjf')
	with open(sfilename, 'w') as sfile:
		sfile.write(scanline)
