#! /usr/bin/env python
# 
#    extractf12: a python script to print the output energy and T1 diagnostic from ORCA single-point calculations from the command line
#    modified from the original function written by Aaron Danilack for use with Molpro output
#    Usage: $ extractf12 file1 file2 ...
#    Copyright (C) 2020  Mark E. Fuller
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#    Mark E. Fuller: mark.e.fuller@gmx.de


#setup terminal output later:
#    extractf12  Copyright (C) 2020  Mark E. Fuller
#    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
#    This is free software, and you are welcome to redistribute it
#    under certain conditions; type `show c' for details.


################################################################################


# Import stuff.
import sys

print '\n'

for filename in sys.argv[1:]: 

	E0 = [] # Fill this list with E0 lines.
	T1 = [] # Fill this list with T1 lines.

	# Get the data from the single-point calculation.
	outfile = open(filename,'r')#(species + '_' + method + '_ccpvtz_f12_tz.out', 'r')
	outlines = outfile.readlines()
	outfile.close()

	for (l,line) in enumerate(outlines):
	    if line.startswith('T1 diagnostic'):
		    T1.append(line)
	    elif line.startswith('FINAL SINGLE POINT ENERGY'):
		    E0.append(line)

	# Print the data we want.
	print filename 
	print 'E0 = ' + str(E0[-1].split()[-1])
	print 'T1 = ' + str(T1[-1].split()[-1])	
	print '\n'                 
